spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mtgdb
    username: mtg_user
    password: mtg_pass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
server:
  port: 8080
jwt:
  secret: very-secret-key-change-me_test!@#$%^&*(
  access-expiration-ms: 900000    # 15 minutes
  refresh-expiration-ms: 604800000  # 7 dias
kafka:
  bootstrap-servers: localhost:9092
